# 🔵 Phase 1 — Baseline Models
##### Establish fair baselines.
#### Experiment 1 — Flat Multiclass (No Balancing)

##### Model: Random Forest
##### Metric: Accuracy, Macro F1, Weighted F1

#### Experiment 2 — Flat Multiclass (Class Weighting)
##### Random Forest + class_weight='balanced'

#### Experiment 3 — Flat Multiclass (Resampling)
##### a- SMOTE, b- Fixed Undersampling + SMOTE-NC, c- Bayesian Optimisation of target count for undersampling + SMOTE-NC

### This shows imbalance impact. 

In [2]:
import sklearn
#Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.under_sampling import RandomUnderSampler
import pandas as pd


data = pd.read_csv('UNSW_NB15.csv')
data = data.sample(n=250000, random_state=42)


# One hot encodin
# Assuming 'data' is your dataset containing both numerical and categorical columns
# Use the appropriate columns that contain categorical data
categorical_cols = ['proto', 'service','state']  # Replace with your categorical column names

# Perform one-hot encoding for categorical columns
data_encoded = pd.get_dummies(data, columns=categorical_cols)

# Split the encoded data into features and target
features_encoded = data_encoded.drop('attack_cat', axis=1)  # Replace 'target_column' with your target column name
target = data_encoded['attack_cat']  # Replace 'target_column' with your target column name
print(target.value_counts())

# Assuming you already have your preprocessed 'features_encoded' and 'target'
# Split the encoded data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features_encoded, target, test_size=0.2, random_state=42)


# Try the RandomForest classifier
rf_classifier = RandomForestClassifier(
   n_estimators=300,       # number of trees
    max_depth=None,         # maximum depth of trees
    random_state=42,
    #class_weight='balanced'
)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)


# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

attack_cat
Normal            90254
Generic           57073
Exploits          43175
Fuzzers           23580
DoS               15834
Reconnaissance    13580
Analysis           2607
Backdoor           2262
Shellcode          1465
Worms               170
Name: count, dtype: int64
Accuracy: 0.87666
Confusion Matrix:
[[  108    89   138   127    36     1     0     6     0     0]
 [   62    51    96   139    15     2     0    73     5     0]
 [  110   111  1157  1439   159    19     0   167    23     0]
 [   80   121  1192  6700   222    20     0   193    27     4]
 [   63    19   158   194  4344     4     0    66    19     0]
 [    2     4    36   147    23 11060     0     4     7     0]
 [    0     0     0     0     0     0 18110     0     0     0]
 [    8    68   179   293    61     3     0  2125     2     0]
 [    0     0     4    39    45     3     0     5   175     1]
 [    0     0     1    28     5     0     0     0     0     3]]
Classification Report:
                precision    reca

In [3]:
import sklearn
#Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.under_sampling import RandomUnderSampler
import pandas as pd


data = pd.read_csv('UNSW_NB15.csv')
data = data.sample(n=250000, random_state=42)


# One hot encodin
# Assuming 'data' is your dataset containing both numerical and categorical columns
# Use the appropriate columns that contain categorical data
categorical_cols = ['proto', 'service','state']  # Replace with your categorical column names

# Perform one-hot encoding for categorical columns
data_encoded = pd.get_dummies(data, columns=categorical_cols)

# Split the encoded data into features and target
features_encoded = data_encoded.drop('attack_cat', axis=1)  # Replace 'target_column' with your target column name
target = data_encoded['attack_cat']  # Replace 'target_column' with your target column name
print(target.value_counts())

# Assuming you already have your preprocessed 'features_encoded' and 'target'
# Split the encoded data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features_encoded, target, test_size=0.2, random_state=42)


# Try the RandomForest classifier
rf_classifier = RandomForestClassifier(
   n_estimators=300,       # number of trees
    max_depth=None,         # maximum depth of trees
    random_state=42,
    class_weight='balanced'
)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)


# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

attack_cat
Normal            90254
Generic           57073
Exploits          43175
Fuzzers           23580
DoS               15834
Reconnaissance    13580
Analysis           2607
Backdoor           2262
Shellcode          1465
Worms               170
Name: count, dtype: int64
Accuracy: 0.87524
Confusion Matrix:
[[  107    89   137   129    36     1     0     6     0     0]
 [   62    55    96   136    14     2     0    72     6     0]
 [  110   111  1135  1460   163    21     0   165    20     0]
 [   81   121  1182  6701   237    18     0   185    29     5]
 [   63    19   158   206  4333     4     0    67    17     0]
 [    2     4    36   164    22 11045     0     3     6     1]
 [    0     0     0     3     0     0 18107     0     0     0]
 [    9    68   179   313    60     3     0  2107     0     0]
 [    0     0     2    36    57     4     0     6   167     0]
 [    0     0     1    26     5     0     0     0     0     5]]
Classification Report:
                precision    reca

In [ ]:
import sklearn
#Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTENC
import pandas as pd


data = pd.read_csv('UNSW_NB15.csv')
data = data.sample(n=250000, random_state=42)


# One hot encodin is not needed when performing SMOTE-NC
# Assuming 'data' is your dataset containing both numerical and categorical columns
# Use the appropriate columns that contain categorical data
# categorical_cols = ['proto', 'service','state']  # Replace with your categorical column names

# Perform one-hot encoding for categorical columns
#data_encoded = pd.get_dummies(data, columns=categorical_cols)

# Split the encoded data into features and target
features_encoded = data_encoded.drop('attack_cat', axis=1)  # Replace 'target_column' with your target column name
target = data_encoded['attack_cat']  # Replace 'target_column' with your target column name
print(target.value_counts())


# Undersample majority classes first
# 
# Assuming you already have your preprocessed 'features_encoded' and 'target'
# Split the encoded data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features_encoded, target, test_size=0.2, random_state=42)

# SMOTE Applied on training set only to prevent data leakage
# Identify categorical column indices (e.g., columns at index 0 and 2)
cat_indices = [2, 3, 4]

# Initialize and fit
smote_nc = SMOTENC(categorical_features=cat_indices, random_state=42)
X_resampled, y_resampled = smote_nc.fit_resample(X_train, y_train)


# Try the RandomForest classifier
rf_classifier = RandomForestClassifier(
   n_estimators=300,       # number of trees
    max_depth=None,         # maximum depth of trees
    random_state=42,
    #class_weight='balanced'
)

rf_classifier.fit(X_resampled, y_resampled)

y_pred = rf_classifier.predict(X_test)


# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

attack_cat
Normal            90254
Generic           57073
Exploits          43175
Fuzzers           23580
DoS               15834
Reconnaissance    13580
Analysis           2607
Backdoor           2262
Shellcode          1465
Worms               170
Name: count, dtype: int64
Accuracy: 0.87322
Confusion Matrix:
[[  127    88   137   112    35     1     0     5     0     0]
 [   69    64   107   106    17     2     0    71     7     0]
 [  149   141  1190  1322   160    18     0   166    39     0]
 [  149   149  1200  6445   283    17     0   205   103     8]
 [   83    57   161   158  4288     5     0    66    48     1]
 [    2     7    40   152    27 11041     0     3     9     2]
 [    0     0     0     0     0     0 18110     0     0     0]
 [   11    67   184   253    60     3     0  2147    13     1]
 [    0     0     0     7    22     2     0     6   235     0]
 [    0     0     1    18     4     0     0     0     0    14]]
Classification Report:
                precision    reca

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTENC
from imblearn.under_sampling import RandomUnderSampler
# ------------------------
# Load data
# ------------------------
data = pd.read_csv('UNSW_NB15.csv')
data = data.sample(n=250000, random_state=42)

features_encoded = data_encoded.drop('attack_cat', axis=1)
target = data_encoded['attack_cat']

# ------------------------
# Train/test split
# ------------------------
X_train, X_test, y_train, y_test = train_test_split(
    features_encoded, target, test_size=0.2, random_state=42, stratify=target
)

# ------------------------
# Step 1: Pure math undersampling
# ------------------------
target_count = 7000  # the max you want per class

# Compute the sampling strategy mathematically
counts = y_train.value_counts()
undersample_dict = {cls: min(count, target_count) for cls, count in counts.items()}

# Apply undersampling
rus = RandomUnderSampler(sampling_strategy=undersample_dict, random_state=42)
X_resampled, y_resampled = rus.fit_resample(X_train, y_train)

print("After undersampling:")
print(pd.Series(y_resampled).value_counts())

# ------------------------
# Step 2: SMOTE up for minority classes
# ------------------------
cat_indices = [2, 3, 4]  # categorical column indices
smote = SMOTENC(categorical_features=cat_indices, sampling_strategy='not majority', random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_resampled, y_resampled)

print("After SMOTE:")
print(pd.Series(y_resampled).value_counts())

# ------------------------
# Step 3: Train model
# ------------------------
model = RandomForestClassifier(n_estimators=200, max_depth=20, random_state=42)
model.fit(X_resampled, y_resampled)

# Add bayesian optimization to get the best target_count value
# ------------------------
# Step 4: Evaluate
# ------------------------
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

After undersampling:
attack_cat
DoS               7000
Exploits          7000
Fuzzers           7000
Generic           7000
Normal            7000
Reconnaissance    7000
Analysis          2086
Backdoor          1810
Shellcode         1172
Worms              136
Name: count, dtype: int64
After SMOTE:
attack_cat
Analysis          7000
Backdoor          7000
DoS               7000
Exploits          7000
Fuzzers           7000
Generic           7000
Normal            7000
Reconnaissance    7000
Shellcode         7000
Worms             7000
Name: count, dtype: int64
Accuracy: 0.8487

Confusion Matrix:
[[  137   152   222    10     0     0     0     0     0     0]
 [   85   163   166    14     5     0     0    14     3     2]
 [  239   423  1936   387    55     5     0    51    55    16]
 [  434   546  2190  4474   226     5     1   437   157   165]
 [   92   196   230    35  4020     0     0    35    96    12]
 [    5    19    68   153    30 11116     0     2    16     6]
 [    0     0     

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from imblearn.over_sampling import SMOTENC
from imblearn.under_sampling import RandomUnderSampler
import optuna

# ------------------------
# Load data
# ------------------------
data = pd.read_csv('UNSW_NB15.csv')
data = data.sample(n=250000, random_state=42)

categorical_cols = ['proto', 'service', 'state']

data_encoded = pd.get_dummies(data, columns=categorical_cols)

features = data_encoded.drop(['attack_cat', 'label'], axis=1)
target = data_encoded['attack_cat']

# ------------------------
# Train/test split
# ------------------------
X_train, X_test, y_train, y_test = train_test_split(
    features, target, test_size=0.2, random_state=42, stratify=target
)

cat_indices = [2, 3, 4]  # categorical column indices

# Make the Objective function
def optuna_obj(trial):

    # Suggest hyperparameters
    target_count = trial.suggest_int("target_count", 1000, 15000)
    n_estimators = trial.suggest_int("n_estimators", 100, 500)
    max_depth = trial.suggest_int("max_depth", 5, 30)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)

    counts = y_train.value_counts()

    undersample_dict = {cls: min(count, target_count) for cls, count in counts.items()}

    smote = SMOTENC(categorical_features=cat_indices, sampling_strategy='not majority', random_state=42)

    # Apply undersampling
    rus = RandomUnderSampler(sampling_strategy=undersample_dict, random_state=42)
    X_resampled, y_resampled = rus.fit_resample(X_train, y_train)
    print("After undersampling:")
    print(pd.Series(y_resampled).value_counts())
    X_resampled, y_resampled = smote.fit_resample(X_resampled, y_resampled)

    print("After SMOTE:")
    print(pd.Series(y_resampled).value_counts())

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=42,
        n_jobs=-1
    )
    model.fit(X_resampled, y_resampled)

    y_pred = model.predict(X_test)
    f1 = f1_score(y_test, y_pred)
    print("f1_score:", f1)

    return f1

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score
import numpy as np

def objective(trial):

    target_count = trial.suggest_int("target_count", 1000, 15000)
    n_estimators = trial.suggest_int("n_estimators", 100, 500)
    max_depth = trial.suggest_int("max_depth", 5, 30)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)

    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    fold_scores = []

    for train_idx, val_idx in skf.split(X_train, y_train):

        X_tr = X_train.iloc[train_idx]
        y_tr = y_train.iloc[train_idx]

        X_val_fold = X_train.iloc[val_idx]
        y_val_fold = y_train.iloc[val_idx]

        # ✅ Compute counts from THIS fold only
        counts = y_tr.value_counts()

        undersample_dict = {
            cls: min(count, target_count)
            for cls, count in counts.items()
        }

        # ---------------- UnderSampling ----------------
        rus = RandomUnderSampler(
            sampling_strategy=undersample_dict,
            random_state=42
        )

        X_res, y_res = rus.fit_resample(X_tr, y_tr)

        # ---------------- SMOTE ----------------
        smote = SMOTENC(
            categorical_features=cat_indices,
            sampling_strategy="not majority",
            random_state=42
        )

        X_res, y_res = smote.fit_resample(X_res, y_res)

        # ---------------- Model ----------------
        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            random_state=42,
            n_jobs=-1
        )

        model.fit(X_res, y_res)

        preds = model.predict(X_val_fold)

        fold_scores.append(
            f1_score(y_val_fold, preds, average="weighted")
        )

    return np.mean(fold_scores)


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=30)

print("Best target_count:", study.best_params)
print("Best Weighted F1:", study.best_value)


C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-02-21 13:47:05,056] A new study created in memory with name: no-name-26c995a5-d8f8-453f-8871-dfd9f81b7bfa
[I 2026-02-21 13:48:39,129] Trial 0 finished with value: 0.7545945654933434 and parameters: {'target_count': 4303, 'n_estimators': 254, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 0 with value: 0.7545945654933434.
[I 2026-02-21 13:51:53,845] Trial 1 finished with value: 0.7933026973942638 and parameters: {'target_count': 8063, 'n_estimators': 414, 'max_depth': 20, 'min_samples_split': 3}. Best is trial 1 with value: 0.7933026973942638.
[I 2026-02-21 13:54:13,405] Trial 2 finished with value: 0.781128107192328 and parameters: {'

Best target_count: {'target_count': 14975, 'n_estimators': 365, 'max_depth': 27, 'min_samples_split': 7}
Best Weighted F1: 0.8117366187137491


ImportError: Tried to import 'plotly' but failed. Please make sure that the package is installed correctly to use this feature. Actual error: No module named 'plotly'.

In [1]:
import optuna.visualization as vis

fig = vis.plot_optimization_history(study)
fig.show()

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


NameError: name 'study' is not defined